In [4]:
import pandas as pd
data_frame = pd.read_csv('players_22.csv')
data_frame.shape

/var/folders/7g/34v84b9d3k18nb8g6d11b_1h0000gn/T/ipykernel_45458/4006088467.py:2: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  data_frame = pd.read_csv('players_22.csv')

(19239, 110)

In [5]:
data_frame.describe()

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
count,19239.000000,19239.000000,19239.000000,1.916500e+04,19178.000000,19239.000000,19239.000000,19239.000000,19178.000000,19178.000000,...,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,19239.000000,2132.000000
mean,231468.086959,65.772182,71.079370,2.850452e+06,9017.989363,25.210822,181.299704,74.943032,50580.498123,1.354364,...,57.929830,46.601746,48.045584,45.906700,16.406102,16.192474,16.055356,16.229274,16.491814,36.439962
std,27039.717497,6.880232,6.086213,7.613700e+06,19470.176724,4.748235,6.863179,7.069434,54401.868535,0.747865,...,12.159326,20.200807,21.232718,20.755683,17.574028,16.839528,16.564554,17.059779,17.884833,10.751563
min,41.000000,47.000000,49.000000,9.000000e+03,500.000000,16.000000,155.000000,49.000000,1.000000,1.000000,...,12.000000,4.000000,5.000000,5.000000,2.000000,2.000000,2.000000,2.000000,2.000000,15.000000
25%,214413.500000,61.000000,67.000000,4.750000e+05,1000.000000,21.000000,176.000000,70.000000,479.000000,1.000000,...,50.000000,29.000000,28.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000,27.000000
50%,236543.000000,66.000000,71.000000,9.750000e+05,3000.000000,25.000000,181.000000,75.000000,1938.000000,1.000000,...,59.000000,52.000000,56.000000,53.000000,11.000000,11.000000,11.000000,11.000000,11.000000,36.000000
75%,253532.500000,70.000000,75.000000,2.000000e+06,8000.000000,29.000000,186.000000,80.000000,111139.000000,1.000000,...,66.000000,63.000000,65.000000,63.000000,14.000000,14.000000,14.000000,14.000000,14.000000,45.000000
max,264640.000000,93.000000,95.000000,1.940000e+08,350000.000000,54.000000,206.000000,110.000000,115820.000000,5.000000,...,96.000000,93.000000,93.000000,92.000000,91.000000,92.000000,93.000000,92.000000,90.000000,65.000000

In [6]:
data_frame.values

array([[158023, 'https://sofifa.com/player/158023/lionel-messi/220002',
        'L. Messi', ..., 'https://cdn.sofifa.net/flags/fr.png',
        'https://cdn.sofifa.net/teams/1369/60.png',
        'https://cdn.sofifa.net/flags/ar.png'],
       [188545,
        'https://sofifa.com/player/188545/robert-lewandowski/220002',
        'R. Lewandowski', ..., 'https://cdn.sofifa.net/flags/de.png',
        'https://cdn.sofifa.net/teams/1353/60.png',
        'https://cdn.sofifa.net/flags/pl.png'],
       [20801,
        'https://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/220002',
        'Cristiano Ronaldo', ...,
        'https://cdn.sofifa.net/flags/gb-eng.png',
        'https://cdn.sofifa.net/teams/1354/60.png',
        'https://cdn.sofifa.net/flags/pt.png'],
       ...,
       [262760, 'https://sofifa.com/player/262760/nathan-logue/220002',
        'N. Logue', ..., 'https://cdn.sofifa.net/flags/ie.png', nan,
        'https://cdn.sofifa.net/flags/ie.png'],
       [262820, 'https://sofifa.com/player/262820/luke-rudden/220002',
        'L. Rudden', ..., 'https://cdn.sofifa.net/flags/ie.png', nan,
        'https://cdn.sofifa.net/flags/ie.png'],
       [264540,
        'https://sofifa.com/player/264540/emanuel-lalchhanchhuaha/220002',
        'E. Lalchhanchhuaha', ..., 'https://cdn.sofifa.net/flags/in.png',
        nan, 'https://cdn.sofifa.net/flags/in.png']], dtype=object)